const actionType={
    // carousel
    GET_CAROUSEL:"GET_CAROUSEL",
    // movie
    GET_MOVIE_LIST:"GET_MOVIE_LIST",
    GET_MOVIE_DANGCHIEU:"GET_MOVIE_DANGCHIEU",
    GET_MOVIE_SAPCHIEU:"GET_MOVIE_SAPCHIEU",
    GET_MOVIE_HOT:"GET_MOVIE_HOT",
    GET_DETAIL_MOVIE:"GET_DETAIL_MOVIE",
    // cinema
    GET_LAYDANHSACH_CUMRAP:"GET_LAYDANHSACH_CUMRAP",
    // account
    SET_ME:"SET_ME",
}
export default actionType;